= AKS Node Maintenance

== Cluster Upgrade and Node Maintenance

AKS allows you to upgrade your Kubernetes control-plane and nodes.
See https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster[Upgrade an Azure Kubernetes Service (AKS) cluster]
Node Images can also be upgraded. AKS provides one new image per week with the latest updates,
See https://docs.microsoft.com/en-us/azure/aks/node-image-upgrade[Azure Kubernetes Service (AKS) node image upgrade]
Also Check https://github.com/Azure/AKS/releases[AKS Release Notes] for details on a Release.


=== Kubernetes Control Plane upgrade

Change the parameter `cluster_version` in your `aks-terraform` repository to change the Kubernetes version.
When applied, AKS starts with the upgrade process as described https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#upgrade-an-aks-cluster[ḧere]


=== Node Image Upgrade

Check latest node image version available for your node pool with the following command:

----
az aks nodepool get-upgrades \
    --nodepool-name mynodepool \
    --cluster-name myAKSCluster \
    --resource-group myResourceGroup
----

Then compare this with your current node image version by running:

----
az aks nodepool show \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --name mynodepool \
    --query nodeImageVersion
----

To upgrade the node image, use the following command:

----
az aks nodepool upgrade \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --name mynodepool \
    --node-image-only
----

During the upgrade, check the status of the node images with the following `kubectl` command to get the labels and filter out the current node image information:

----
kubectl get nodes -o jsonpath='{range .items[*]}{.metadata.name}{"\t"}{.metadata.labels.kubernetes\.azure\.com\/node-image-version}{"\n"}{end}'
----


=== Script for automated update


----
#!/bin/bash

usage () {
    cat <<HELP_USAGE
    This script requires the following arguments:
    $0 <resource-group> <cluster-name> <nodepool-name> [apply]
    Use 'apply' to execute upgrade.
HELP_USAGE
}

if [  $# -le 2 ] 
	then 
		usage
		exit 1
	fi 

if ! command -v jq &> /dev/null
then
    echo "Cannot run $0. This scripts requires 'jq'. Please install 'jq' first!"
    exit
fi

if ! command -v az &> /dev/null
then
    echo "Cannot run $0. This scripts requires 'az'. Please install 'az' first!"
    exit
fi

RESOURCE_GROUP=$1
CLUSTER_NAME=$2
NODE_POOL=$3
APPLY=$4

echo "Checking nodepool image upgrade"
echo "  Resource group: '$RESOURCE_GROUP'";
echo "  Cluster name: '$CLUSTER_NAME'";
echo "  Nodepool: '$NODE_POOL'";


LATEST_VERSION=$(az aks nodepool get-upgrades --resource-group $RESOURCE_GROUP --cluster-name $CLUSTER_NAME --nodepool-name $NODE_POOL --only-show-errors | jq -r ".latestNodeImageVersion")
CURRENT_VERSION=$(az aks nodepool show --resource-group $RESOURCE_GROUP --cluster-name $CLUSTER_NAME --name $NODE_POOL --query nodeImageVersion --only-show-errors | sed 's/"//g')

echo ""
echo "Latest nodepool image version: '$LATEST_VERSION'"
echo "Curent nodepool image version: '$CURRENT_VERSION'"
echo ""

if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
    echo "-> Nodepool image upgrade required, upgrading.. please wait.."

    if [ "$APPLY" == "apply" ]; then
        az aks nodepool upgrade --resource-group $RESOURCE_GROUP --cluster-name $CLUSTER_NAME --name $NODE_POOL --node-image-only
        echo "-> Nodepool image upgrade done"
    fi
else
    echo "-> Nodepool image upgrade not required"
fi
----