= K3S Maintenance

== Kubernetes Maintenance

The Kubernetes version is bound to the K3S version, so by updating K3S you also update the Kubernetes version.
The https://github.com/rancher/system-upgrade-controller[System Upgrade Controller] from Rancher is used to upgrade the K3S version.
The System Upgrade Controller is installed using a https://github.com/projectsyn/component-system-upgrade-controller[Project Syn component]

In order to manage the K3S version the following System Upgrade Controller plan is used (the plan is also installed using the Project Syn component):

[source,yaml]
----
include::example$suc_plan_k3s.yaml[]
----

Check the https://github.com/k3s-io/k3s/releases[K3S Release] page and update the value `version` with the version you want to upgrade to. Example: `version: v1.20.4+k3s1`

This will immediatly trigger an upgrade of K3S. The container image `docker.io/rancher/k3s-upgrade` will replace the existing K3S binary and restart K3S.

== Node Maintenance

We use Ubuntu as the underlaying operating system for K3S Kubernetes clusters. Node maintenance is also done using the System Upgrade Controller. 
To upgrade the system packages the following scripts in a container image are used: https://github.com/projectsyn/system-upgrade-controller-package-upgrade
Every week a new container image is build with the updates os packages. This container image is used in the System Upgrade Controller plan.

The following System Upgrade Controller plan is used (the plan is also installed using the Project Syn component):

[source,yaml]
----
include::example$suc_plan_os.yaml[]
----

This plan uses a `channel` instead of the `version` argument. The Project Syn component configures this to the https://github.com/projectsyn/floodgate[Floodgate URL]: `https://floodgate.syn.vshn.net/window/<day>/<hour>`
Floodate returns the version of the upgrade container to be used. The time of upgrade is controller with the `day` and `hour` variable. An update to the latest OS package version is only done after this time.

In order to upgrade K3S nodes using the System Upgrade Controller, they have to be labeled with `plan.upgrade.cattle.io/focal`